#! /bin/sh
#
# $Id: vinstall,v 1.3 2001-04-28 15:57:36 jle Exp $

if [ -n "$VRP_STRIPTOOL" ]; then
  $VRP_STRIPTOOL src/npuzzle
fi
mkdir ${VRP_FAKE_ROOT_DIR}/usr || true
mkdir ${VRP_FAKE_ROOT_DIR}/usr/bin || true
cp src/npuzzle ${VRP_FAKE_ROOT_DIR}/usr/bin/ && \
  chmod a+rx ${VRP_FAKE_ROOT_DIR}/usr/bin/npuzzle
