// generated by Fast Light User Interface Designer (fluid) version 1.0009

#include "FileChooser.h"

inline void FileChooser::cb_window_i(Fl_Window*, void*) {
  fileList->deselect();
fileName->value("");
window->hide();
}
void FileChooser::cb_window(Fl_Window* o, void* v) {
  ((FileChooser*)(o->user_data()))->cb_window_i(o,v);
}

inline void FileChooser::cb_fileList_i(FileBrowser*, void*) {
  fileListCB();
}
void FileChooser::cb_fileList(FileBrowser* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_fileList_i(o,v);
}

inline void FileChooser::cb_Cancel_i(Fl_Button*, void*) {
  fileList->deselect();
fileName->value("");
window->hide();
}
void FileChooser::cb_Cancel(Fl_Button* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_Cancel_i(o,v);
}

inline void FileChooser::cb_okButton_i(Fl_Button*, void*) {
  window->hide();
}
void FileChooser::cb_okButton(Fl_Button* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_okButton_i(o,v);
}

inline void FileChooser::cb_fileName_i(FileInput*, void*) {
  fileNameCB();
}
void FileChooser::cb_fileName(FileInput* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_fileName_i(o,v);
}

inline void FileChooser::cb_upButton_i(Fl_Button*, void*) {
  up();
}
void FileChooser::cb_upButton(Fl_Button* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_upButton_i(o,v);
}

#include <FL/Fl_Bitmap.H>
static unsigned char bits_up[] =
"\34\0""6\0\343\17\1\b1\by\b\375\b1\b1\b1\b\1\b\377\17";
static Fl_Bitmap bitmap_up(bits_up, 12, 12);

inline void FileChooser::cb_newButton_i(Fl_Button*, void*) {
  newdir();
}
void FileChooser::cb_newButton(Fl_Button* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_newButton_i(o,v);
}

static unsigned char bits_new[] =
"\34\0""6\0\343\17\1\b1\b1\b\375\b\375\b1\b1\b\1\b\377\17";
static Fl_Bitmap bitmap_new(bits_new, 12, 12);

inline void FileChooser::cb_dirMenu_i(Fl_Choice*, void*) {
  char pathname[1024];
int i;

pathname[0] = '\0';
for (i = 1; i <= dirMenu->value(); i ++)
  strcat(pathname, dirMenu->text(i));
directory(pathname);
}
void FileChooser::cb_dirMenu(Fl_Choice* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_dirMenu_i(o,v);
}

inline void FileChooser::cb_allfiles_i(Fl_Button*, void*) {
  fileList->filter("*");;
rescan();
}
void FileChooser::cb_allfiles(Fl_Button* o, void* v) {
  ((FileChooser*)(o->parent()->user_data()))->cb_allfiles_i(o,v);
}

static unsigned char bits_allfiles[] =
"\377\17\1\ba\bi\t\361\b\375\13\375\13\361\bi\ta\b\1\b\377\17";
static Fl_Bitmap bitmap_allfiles(bits_allfiles, 12, 12);

FileChooser::FileChooser(const char *d, const char *p, int t, const char *title) {
  Fl_Window* w;
  { Fl_Window* o = window = new Fl_Window(160, 240, "Pick a File");
    w = o;
    o->callback((Fl_Callback*)cb_window, (void*)(this));
    w->hotspot(o);
    { FileBrowser* o = fileList = new FileBrowser(0, 45, 160, 155);
      o->type(2);
      o->labelsize(10);
      o->textsize(10);
      o->callback((Fl_Callback*)cb_fileList);
      Fl_Group::current()->resizable(o);
      w->hotspot(o);
    }
    { Fl_Button* o = new Fl_Button(35, 225, 35, 15, "Cancel");
      o->labelsize(10);
      o->callback((Fl_Callback*)cb_Cancel);
    }
    { Fl_Button* o = okButton = new Fl_Button(0, 225, 35, 15, "OK");
      o->labelsize(10);
      o->callback((Fl_Callback*)cb_okButton);
    }
    { FileInput* o = fileName = new FileInput(5, 205, 150, 15);
      o->labelsize(10);
      o->textsize(10);
      o->callback((Fl_Callback*)cb_fileName);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_ENTER_KEY);
      fileName->when(FL_WHEN_CHANGED | FL_WHEN_ENTER_KEY_ALWAYS);
    }
    { Fl_Button* o = upButton = new Fl_Button(100, 25, 15, 15);
      bitmap_up.label(o);
      o->labelsize(8);
      o->callback((Fl_Callback*)cb_upButton);
    }
    { Fl_Button* o = newButton = new Fl_Button(120, 25, 15, 15);
      bitmap_new.label(o);
      o->labelsize(8);
      o->callback((Fl_Callback*)cb_newButton);
    }
    { Fl_Choice* o = dirMenu = new Fl_Choice(55, 5, 100, 15, "Directory:");
      o->labelsize(10);
      o->textsize(10);
      o->callback((Fl_Callback*)cb_dirMenu);
    }
    { Fl_Button* o = new Fl_Button(140, 25, 15, 15);
      bitmap_allfiles.label(o);
      o->labelsize(28);
      o->labelcolor(4);
      o->callback((Fl_Callback*)cb_allfiles);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    if (title) window->label(title);
    o->set_modal();
    o->end();
  }
  fileList->filter(p);
type(t);
value(d);
}

void FileChooser::color(Fl_Color c) {
  fileList->color(c);
}

Fl_Color FileChooser::color() {
  return (fileList->color());
}

char * FileChooser::directory() {
  return directory_;
}

void FileChooser::filter(const char *p) {
  fileList->filter(p);
rescan();
}

const char * FileChooser::filter() {
  return (fileList->filter());
}

void FileChooser::hide() {
  window->hide();
}

void FileChooser::iconsize(uchar s) {
  fileList->iconsize(s);
}

uchar FileChooser::iconsize() {
  return (fileList->iconsize());
}

void FileChooser::label(const char *l) {
  window->label(l);
}

const char * FileChooser::label() {
  return (window->label());
}

void FileChooser::show() {
  window->show();
fileList->deselect();
}

void FileChooser::textcolor(Fl_Color c) {
  fileList->textcolor(c);
}

Fl_Color FileChooser::textcolor() {
  return (fileList->textcolor());
}

void FileChooser::textfont(uchar f) {
  fileList->textfont(f);
}

uchar FileChooser::textfont() {
  return (fileList->textfont());
}

void FileChooser::textsize(uchar s) {
  fileList->textsize(s);
}

uchar FileChooser::textsize() {
  return (fileList->textsize());
}

void FileChooser::type(int t) {
  type_ = t;
if (t == MULTI)
  fileList->type(FL_MULTI_BROWSER);
else
  fileList->type(FL_HOLD_BROWSER);
if (t != CREATE)
  newButton->deactivate();
else
  newButton->activate();
}

int FileChooser::type() {
  return (type_);
}

int FileChooser::visible() {
  return window->visible();
}
